### ISSUE TITLE
编了个OrangeFox的Recovery - lcblues(lyq1996)的博客

### ISSUE THREAD

**Issue by lyq1996** [lyq1996/comments#9]
https://lyq.blogd.club/2020/02/15/fox-rec/ 

 基于TWRP修改的，界面挺帅。   遇到的问题： /sbin/start找不到 系统开机卡在壁纸界面 app manager用不了 中文字体显示不了  解决 系统开机卡在壁纸页面翻看log发现是xposed的问题，我透。下了Magisk_Manager_Recovery把太极禁用了就好了。  慢慢修

**Comment by lyq1996** [comment]
真的吓人，我寻思刷个recovery分区，也不该对系统有影响啊！

**Comment by NavlysChen** [comment]
请问一下，r10.1的源码在哪里？我找到的是9.0的。。。

**Comment by lyq1996** [comment]
> @NavlysChen
> 请问一下，r10.1的源码在哪里？我找到的是9.0的。。。
看这里

https://gitlab.com/OrangeFox/bootable/Recovery/-/tree/R10.1

**Comment by NavlysChen** [comment]
> @lyq1996
> > @NavlysChen
> > 请问一下，r10.1的源码在哪里？我找到的是9.0的。。。
> 看这里
> 
> https://gitlab.com/OrangeFox/bootable/Recovery/-/tree/R10.1
> 

非常感谢
